# https://github.com/SeleniumHQ/docker-selenium

services:
  chrome:
    image: selenium/node-chrome:4.27.0-20241127
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
    ports:
      - "7901:7900"

  edge:
    image: selenium/node-edge:4.27.0-20241127
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
    ports:
      - "7902:7900"

  firefox:
    image: selenium/node-firefox:4.27.0-20241127
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
    ports:
      - "7903:7900"

  selenium-hub:
    image: selenium/hub:4.27.0-20241127
    container_name: selenium-hub
    environment:
      - SE_ENABLE_TRACING=false
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

# docker compose up -d
